#!/bin/bash

set -e

command -v java >/dev/null 2>&1 || { echo >&2 "Java 8 is required for running. Aborting."; exit 1; }

cd game-server/

# If you pass -r, reset the server database
if [ "$1" = "-r" ]; then
    rm server.db
fi

java -jar tak-server.jar
